# Generated by Django 4.2.21 on 2025-06-03 17:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_enhance_profile_with_user_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="profile",
            new_name="api_profile_user_id_bc09a5_idx",
            old_name="api_profile_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="profile",
            new_name="api_profile_email_ed681b_idx",
            old_name="api_profile_email_idx",
        ),
        migrations.AddField(
            model_name="loan",
            name="collateral_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Current value of collateral securing this loan",
                max_digits=15,
            ),
        ),
    ]
