# Generated by Fedha encryption planning
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_enhancedtransaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKeyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=20)),
                ('key_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_master_key', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyRotationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_version', models.PositiveIntegerField()),
                ('new_version', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=20)),
                ('fields_reencrypted', models.JSONField(default=list, blank=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
