# Generated by assistant: add encrypted PII binary fields and encryption_version
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_key_management_models'),
    ]

    operations = [
        # Profile
        migrations.AddField(
            model_name='profile',
            name='email_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='encryption_version',
            field=models.PositiveIntegerField(default=1, help_text='Encryption key version used for encrypted fields'),
        ),

        # Client
        migrations.AddField(
            model_name='client',
            name='name_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='encryption_version',
            field=models.PositiveIntegerField(default=1, help_text='Encryption key version used for encrypted fields'),
        ),

        # EnhancedTransaction
        migrations.AddField(
            model_name='enhancedtransaction',
            name='reference_number_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='enhancedtransaction',
            name='receipt_url_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='enhancedtransaction',
            name='encryption_version',
            field=models.PositiveIntegerField(default=1, help_text='Encryption key version used for encrypted fields'),
        ),

        # Loan
        migrations.AddField(
            model_name='loan',
            name='account_number_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='lender_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='encryption_version',
            field=models.PositiveIntegerField(default=1, help_text='Encryption key version used for encrypted fields'),
        ),

        # AuditLog: add encrypted field_changes as blob as optional
        migrations.AddField(
            model_name='auditlog',
            name='field_changes_encrypted',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
    ]
