# Generated by Django 4.2.23 on 2025-11-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_add_profile_fk_to_key_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="encryptionkeyversion",
            options={"ordering": ["-version"]},
        ),
        migrations.AlterModelOptions(
            name="keyrotationlog",
            options={"ordering": ["-started_at"]},
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="field_changes_encrypted",
        ),
        migrations.AlterField(
            model_name="keyrotationlog",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled Rotation"),
                    ("EMERGENCY", "Emergency Rotation"),
                    ("COMPROMISE", "Key Compromise"),
                    ("POLICY", "Policy Update"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="keyrotationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=11,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="encryptionkeyversion",
            unique_together={("profile", "version")},
        ),
    ]
