# Generated by Django 6.0 on 2025-12-22 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_name_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
