# Generated by Django 6.0 on 2026-01-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_fix_preferences_json"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="categories_profile_48548d_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="categories_type_735b1a_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="categories_is_acti_aae090_idx",
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_profile_category_name",
        ),
        migrations.DeleteModel(
            name="DefaultCategory",
        ),
        migrations.RemoveField(
            model_name="category",
            name="profile",
        ),
    ]
