# Generated by Django 6.0 on 2026-01-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_category_categories_profile_48548d_idx_and_more"),
        ("budgets", "0003_alter_budget_category"),
        ("transactions", "0003_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
