# Generated by Django 6.0 on 2026-01-03 20:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("budget_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_synced", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets",
                        to="categories.category",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "budgets",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["profile"], name="budgets_profile_67c016_idx"),
                    models.Index(
                        fields=["category"], name="budgets_categor_d644d8_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="budgets_is_acti_676e28_idx"
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="budgets_start_d_6720b3_idx",
                    ),
                    models.Index(
                        fields=["is_synced"], name="budgets_is_sync_2078dd_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("budget_amount__gt", 0)),
                        name="budget_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("spent_amount__gte", 0)),
                        name="spent_amount_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="end_after_start",
                    ),
                ],
            },
        ),
    ]
