# Generated by Django 6.0 on 2026-01-10 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.CharField(default="KES", max_length=3),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__in", ["KES", "USD", "EUR", "GBP"])),
                name="valid_currency",
            ),
        ),
    ]
