# Generated by Django 6.0 on 2026-01-03 22:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(max_length=7)),
                ("icon", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "Default Categories",
                "db_table": "default_categories",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, db_column="icon_name", max_length=100, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("savings", "Savings"),
                        ],
                        default="expense",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_synced", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, this is a global/default category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["profile"], name="idx_categories_profile_id"),
                    models.Index(fields=["type"], name="idx_categories_type"),
                    models.Index(fields=["is_active"], name="categories_is_active_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "name"), name="unique_profile_category_name"
                    )
                ],
            },
        ),
    ]
