targets:
  $default:
    builders:
      hive_generator:hive_generator:
        options:
          create_to_json: true
          create_from_json: true
        generate_for:
          - lib/models/*.dart
      json_serializable:serializable:
        options:
          any_map: true
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake_case
          generic_argument_factories: false
          include_if_null: true
        generate_for:
          - lib/models/*.dart
