# Generated by Django 6.0 on 2026-01-03 20:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings"),
                            ("debtReduction", "Debt Reduction"),
                            ("insurance", "Insurance"),
                            ("emergencyFund", "Emergency Fund"),
                            ("investment", "Investment"),
                            ("other", "Other"),
                        ],
                        default="savings",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_column="goal_status",
                        default="active",
                        max_length=50,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("target_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("last_contribution_date", models.DateTimeField(blank=True, null=True)),
                ("contribution_count", models.IntegerField(default=0)),
                (
                    "average_contribution",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "linked_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "projected_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("days_ahead_behind", models.IntegerField(blank=True, null=True)),
                ("goal_group", models.CharField(blank=True, max_length=100, null=True)),
                ("remote_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "goals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["profile"], name="goals_profile_5a9a0a_idx"),
                    models.Index(
                        fields=["profile", "status"], name="goals_profile_43987a_idx"
                    ),
                    models.Index(fields=["status"], name="goals_goal_st_6cddae_idx"),
                    models.Index(fields=["goal_type"], name="goals_goal_ty_2de6ae_idx"),
                    models.Index(
                        fields=["target_date"], name="goals_target__152f3a_idx"
                    ),
                    models.Index(
                        fields=["linked_category"], name="goals_linked__17c939_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("current_amount__lte", models.F("target_amount")),
                            ("status", "completed"),
                            _connector="OR",
                        ),
                        name="goals_check",
                    )
                ],
            },
        ),
    ]
