# Generated by Django 6.0 on 2025-12-20 20:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("target_date", models.DateTimeField()),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings"),
                            ("debtReduction", "Debt Reduction"),
                            ("insurance", "Insurance"),
                            ("emergencyFund", "Emergency Fund"),
                            ("investment", "Investment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_synced", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "goals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["profile"], name="goals_profile_5a9a0a_idx"),
                    models.Index(fields=["status"], name="goals_status_6bb941_idx"),
                    models.Index(fields=["goal_type"], name="goals_goal_ty_2de6ae_idx"),
                    models.Index(fields=["is_synced"], name="goals_is_sync_f57b04_idx"),
                    models.Index(
                        fields=["target_date"], name="goals_target__152f3a_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("target_amount__gt", 0), ("current_amount__gte", 0)
                        ),
                        name="goal_amounts_positive",
                    )
                ],
            },
        ),
    ]
