# Generated by Django 6.0 on 2026-01-03 12:34

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="goal",
            name="goal_amounts_positive",
        ),
        migrations.RemoveIndex(
            model_name="goal",
            name="goals_is_sync_f57b04_idx",
        ),
        migrations.RenameIndex(
            model_name="goal",
            new_name="goals_goal_st_6cddae_idx",
            old_name="goals_status_6bb941_idx",
        ),
        migrations.AddField(
            model_name="goal",
            name="average_contribution",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="contribution_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="goal",
            name="currency",
            field=models.CharField(default="KES", max_length=3),
        ),
        migrations.AddField(
            model_name="goal",
            name="days_ahead_behind",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="goal_group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="last_contribution_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="linked_category_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="projected_completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="remote_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="current_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("savings", "Savings"),
                    ("debtReduction", "Debt Reduction"),
                    ("insurance", "Insurance"),
                    ("emergencyFund", "Emergency Fund"),
                    ("investment", "Investment"),
                    ("other", "Other"),
                ],
                default="savings",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("paused", "Paused"),
                    ("cancelled", "Cancelled"),
                ],
                db_column="goal_status",
                default="active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="target_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["profile", "status"], name="goals_profile_43987a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["linked_category_id"], name="goals_linked__ed9677_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_amount__gt", 0)),
                name="goal_amounts_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_amount__lte", models.F("target_amount")),
                    ("status", "completed"),
                    _connector="OR",
                ),
                name="goal_current_amount_check",
            ),
        ),
        migrations.RemoveField(
            model_name="goal",
            name="is_synced",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="priority",
        ),
    ]
