# Generated by Django 6.0 on 2026-01-03 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("goals", "0002_sync_with_database"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="goal",
            name="goal_amounts_positive",
        ),
        migrations.RemoveConstraint(
            model_name="goal",
            name="goal_current_amount_check",
        ),
        migrations.RemoveIndex(
            model_name="goal",
            name="goals_linked__ed9677_idx",
        ),
        migrations.AddField(
            model_name="goal",
            name="linked_category",
            field=models.ForeignKey(
                blank=True,
                db_column="linked_category_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["linked_category"], name="goals_linked__ed9677_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_amount__lte", models.F("target_amount")),
                    ("status", "completed"),
                    _connector="OR",
                ),
                name="goals_check",
            ),
        ),
        migrations.RemoveField(
            model_name="goal",
            name="linked_category_id",
        ),
    ]
