# Generated by Django 6.0 on 2026-01-03 16:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_remove_goal_goal_amounts_positive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
