# Generated by Django 6.0 on 2026-01-03 20:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category name as string (not ForeignKey)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "goal_id",
                    models.CharField(
                        blank=True,
                        help_text="Goal name or ID as string (not ForeignKey)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        help_text="Goal name or ID as string (not ForeignKey)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_synced", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("savings", "Savings"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("bank", "Bank"),
                            ("mobile", "Mobile"),
                            ("online", "Online"),
                            ("cheque", "Cheque"),
                            ("mpesa", "Mpesa"),
                            ("bank_transfer", "Bank Transfer"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("recipient", models.CharField(blank=True, max_length=255, null=True)),
                ("sms_source", models.TextField(blank=True, null=True)),
                (
                    "date",
                    models.DateTimeField(
                        db_column="date", default=django.utils.timezone.now
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurring_pattern",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "merchant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "merchant_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated tags for categorizing transactions",
                        max_length=500,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "anomaly_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "budget_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("budget_id", models.UUIDField(blank=True, null=True)),
                (
                    "budget_category_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remote_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_pending", models.BooleanField(default=False)),
                ("is_expense", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_transactions",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PendingTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=255, null=True)),
                ("raw_text", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "date",
                    models.DateTimeField(
                        db_column="date", default=django.utils.timezone.now
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("savings", "Savings"),
                            ("transfer", "Transfer"),
                        ],
                        default="expense",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.5"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_source",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "pending_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["profile"], name="transaction_profile_f84f7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category"], name="transaction_categor_45fcdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["goal"], name="transaction_goal_93622b_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["date"], name="transaction_date_7edf95_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["type"], name="transaction_type_840495_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="transaction_status_505a2f_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["profile", "-date"], name="transaction_profile_9f3131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["anomaly_score"], name="idx_transactions_anomaly"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["budget_id"], name="idx_transactions_budget_id"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["location"], name="idx_transactions_location"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["merchant_name"], name="idx_transactions_merchant"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("anomaly_score__gte", 0), ("anomaly_score__lte", 1)),
                    ("anomaly_score__isnull", True),
                    _connector="OR",
                ),
                name="transactions_anomaly_score_check",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingtransaction",
            index=models.Index(
                fields=["profile"], name="pending_tra_profile_c291ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingtransaction",
            index=models.Index(fields=["status"], name="pending_tra_status_0c404c_idx"),
        ),
        migrations.AddIndex(
            model_name="pendingtransaction",
            index=models.Index(
                fields=["-created_at"], name="pending_tra_created_5f4bd8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="confidence_range",
            ),
        ),
    ]
