# Generated by Django 6.0 on 2026-01-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="budget_category_id",
            new_name="budget_category",
        ),
    ]
