# Generated by Django 6.0 on 2026-01-03 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("goals", "0003_remove_goal_goal_amounts_positive_and_more"),
        (
            "transactions",
            "0002_remove_transaction_transaction_is_sync_1d8a82_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="anomaly_score_range",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_transac_0d716a_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_profile_10e23e_idx",
        ),
        migrations.RemoveField(
            model_name="pendingtransaction",
            name="transaction_date",
        ),
        migrations.AddField(
            model_name="pendingtransaction",
            name="date",
            field=models.DateTimeField(
                db_column="date", default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="budget_category_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(
                db_column="date", default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="parent_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_transactions",
                to="transactions.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="remote_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pendingtransaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="pendingtransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("savings", "Savings"),
                    ("transfer", "Transfer"),
                ],
                default="expense",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_expense",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("savings", "Savings"),
                    ("transfer", "Transfer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["date"], name="transaction_date_7edf95_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["profile", "-date"], name="transaction_profile_9f3131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["anomaly_score"], name="idx_transactions_anomaly"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["budget_id"], name="idx_transactions_budget_id"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["location"], name="idx_transactions_location"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["merchant_name"], name="idx_transactions_merchant"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("anomaly_score__gte", 0), ("anomaly_score__lte", 1)),
                    ("anomaly_score__isnull", True),
                    _connector="OR",
                ),
                name="transactions_anomaly_score_check",
            ),
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="parent_transaction_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_date",
        ),
    ]
