# Generated by Django 6.0 on 2026-02-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_budget_category_id_transaction_budget_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
