# Generated by Django 6.0 on 2026-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pendingtransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("savings", "Savings"),
                ],
                default="expense",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("savings", "Savings"),
                ],
                max_length=20,
            ),
        ),
    ]
