# Generated by Django 6.0 on 2026-01-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_add_is_synced_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingtransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("savings", "Savings"),
                    ("transfer", "Transfer"),
                ],
                default="expense",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("savings", "Savings"),
                    ("transfer", "Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
