# Generated by Django 6.0 on 2026-01-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_pendingtransaction_type_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated tags for categorizing transactions",
                max_length=500,
            ),
        ),
    ]
