name: Build and Distribute APK via Firebase

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: "3.7.0"  # Ensure Dart SDK 3.7.0+ for pubspec.yaml compatibility
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'  # Use latest stable
        cache: true
        
    - name: Get dependencies
      working-directory: ./app
      run: flutter pub get
      
    - name: Run tests
      working-directory: ./app
      run: flutter test --no-pub --coverage
      
    - name: Analyze code
      working-directory: ./app
      run: flutter analyze
      
    - name: Build APK (Debug)
      working-directory: ./app
      run: flutter build apk --debug --build-name=1.0.${{ github.run_number }} --build-number=${{ github.run_number }}
      
    - name: Build APK (Release)
      working-directory: ./app
      run: flutter build apk --release --build-name=1.0.${{ github.run_number }} --build-number=${{ github.run_number }}
      
    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        groups: testers,internal
        file: app/build/app/outputs/flutter-apk/app-release.apk
        releaseNotes: |
          🚀 New build from commit: ${{ github.sha }}
          
          Changes in this build:
          ${{ github.event.head_commit.message }}
          
          Build triggered by: ${{ github.actor }}
          Branch: ${{ github.ref_name }}
          
    - name: Upload Debug APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/app/outputs/flutter-apk/app-debug.apk
        
    - name: Upload Release APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/app/outputs/flutter-apk/app-release.apk

  notify-success:
    needs: build-android
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Notify success
      run: |
        echo "✅ APK built and distributed successfully!"
        echo "🔗 Check Firebase Console for distribution status"
        
  notify-failure:
    needs: build-android
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Notify failure
      run: |
        echo "❌ APK build failed!"
        echo "📝 Check the workflow logs for details"
