name: Build and Deploy to Firebase App Distribution

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build_android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: "3.7"  # Use Dart SDK 3.7 for compatibility with Flutter 3.16.9  

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      working-directory: ./app
      run: flutter pub get
      
    - name: Run Flutter tests
      working-directory: ./app
      run: flutter test
      
    - name: Build APK
      working-directory: ./app
      run: flutter build apk --release
      
    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        groups: testers
        file: app/build/app/outputs/flutter-apk/app-release.apk
        releaseNotes: |
          🚀 New build from commit ${{ github.sha }}
          
          Changes in this build:
          ${{ github.event.head_commit.message }}
          
          Build Details:
          - Branch: ${{ github.ref_name }}
          - Commit: ${{ github.sha }}
          - Trigger: ${{ github.event_name }}
