name: Build and Deploy to Firebase App Distribution

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build_android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        
    - name: Verify versions
      working-directory: ./app
      run: |
        echo "Flutter version:"
        flutter --version
        echo "Dart version:"
        dart --version
        
    - name: Get Flutter dependencies
      working-directory: ./app
      run: flutter pub get
      
    - name: Setup Node.js for Firebase CLI
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Deploy Firestore Rules
      working-directory: ./app
      run: |
        echo "Deploying Firestore security rules..."
        firebase deploy --only firestore:rules --project fedha-tracker --token ${{ secrets.FIREBASE_TOKEN }}
      
    - name: Run Flutter tests
      working-directory: ./app
      run: flutter test
      
    - name: Build APK
      working-directory: ./app
      run: flutter build apk --release
      
    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        groups: testers
        file: app/build/app/outputs/flutter-apk/app-release.apk
        releaseNotes: |
          🚀 New build from commit ${{ github.sha }}
          
          Changes in this build:
          ${{ github.event.head_commit.message }}
          
          Build Details:
          - Branch: ${{ github.ref_name }}
          - Commit: ${{ github.sha }}
          - Trigger: ${{ github.event_name }}
