name: CI/CD - Test and Deploy

on:
  push:
    branches: [ main ]  # Only deploy on main branch pushes
  pull_request:
    branches: [ main ]  # Only test on PRs
  workflow_dispatch:    # Allow manual triggers from GitHub UI
    inputs:
      deploy_rules:
        description: 'Deploy Firestore rules'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: "3.7.0"
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        cache: true

    - name: Get dependencies
      run: |
        cd app
        flutter pub get

    - name: Run analysis
      run: |
        cd app
        flutter analyze --no-fatal-infos

    - name: Run tests
      run: |
        cd app
        flutter test test/firebase_setup_test.dart

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FEDHA_TRACKER }}

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy Firestore rules (auto on main push)
      run: |
        cd app
        echo "🚀 Deploying Firestore rules..."
        firebase deploy --only firestore:rules --project fedha-tracker --debug
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

  manual_deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_rules == 'true'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FEDHA_TRACKER }}

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy Firestore rules (manual trigger)
      run: |
        cd app
        echo "🚀 Manual deployment of Firestore rules..."
        firebase deploy --only firestore:rules --project fedha-tracker --debug
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
